### ISSUE TITLE
TypeError: Cannot read property 'cli' of undefined

### ISSUE THREAD

**Issue by v1rtl** [gluons/poi-preset-resolve-alias#2]
When I try to start Poi, I get this error:

```sh
> yarn dev
yarn run v1.17.3
$ poi index.html --serve --port 3000
TypeError: Cannot read property 'cli' of undefined
    at PoiCore.extendCLI (/home/v1rtl/Desktop/Coding/test-stuff/rollup-web-setup/node_modules/poi/lib/index.js:260:26)
    at PoiCore.initCLI (/home/v1rtl/Desktop/Coding/test-stuff/rollup-web-setup/node_modules/poi/lib/index.js:151:10)
    at new PoiCore (/home/v1rtl/Desktop/Coding/test-stuff/rollup-web-setup/node_modules/poi/lib/index.js:125:10)
    at main (/home/v1rtl/Desktop/Coding/test-stuff/rollup-web-setup/node_modules/poi/bin/cli.js:13:17)
    at Object.<anonymous> (/home/v1rtl/Desktop/Coding/test-stuff/rollup-web-setup/node_modules/poi/bin/cli.js:28:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My **poi.config.js**:

```js
module.exports = {
	plugins: [
		require('poi-plugin-resolve-alias')({
			'react': 'preact'
		})
	]
}
```

My **package.json**:

```json
{
  "name": "rollup-web-setup",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-react": "^7.0.0",
    "autoprefixer": "^9.6.1",
    "cssnano": "^4.1.10",
    "poi": "^12.7.1",
    "poi-plugin-resolve-alias": "^2.0.0",
    "postcss": "^7.0.17",
    "precss": "^4.0.0"
  },
  "dependencies": {
    "preact": "^10.0.0-rc.1"
  },
  "scripts": {
    "dev": "poi index.html --serve --port 3000"
  }
}
```

My **index.js** file:

```jsx
import React, { render } from 'react'
import './style.css'

render(<h1>Hello World</h1>, document.getElementById('app'))
```

**Comment by gluons** [comment]
I've updated this plugin to support Poi 12.  
Try it. 🙂
